1. Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.**bold text**

In [ ]:
age = input("Enter age: ")

name = input("Enter name: ")

print("Hi, my name is " + name + ", and I am " + age + " years old.")

Enter age: 20
Enter name: Aditi
Hi, my name is Aditi, and I am 20 years old.


2. X="Datascience is used to extract meaningful insights." Split the string.

In [ ]:
txt = "Datascience is used to extract meaningful insights."

x = txt.split()

print(x)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


3. Make a function that gives multiplication of two numbers.

In [ ]:
def Multiply(num1, num2):
    answer = num1 * num2
    return answer

print(Multiply(2, 3))

6


4. Create a Dictionary of 5 States with their capitals. Also print the keys and values.

In [ ]:
dict_state = {'Andhra Pradesh': 'Amaravati', 'Assam': 'Dispur', 'Goa': 'Panaji', 'Madhya Pradesh': 'Bhopal', 'Odisha':"Bhubaneswar"}
print(dict_state)

{'Andhra Pradesh': 'Amaravati', 'Assam': 'Dispur', 'Goa': 'Panaji', 'Madhya Pradesh': 'Bhopal', 'Odisha': 'Bhubaneswar'}


5. Create a list of 1000 numbers using range function.

In [ ]:
tons = list(range(1000))
print(tons)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

6. Create an identity matrix of dimension 4 by 4.

In [ ]:
def Identity(size):
    for row in range(0, size):
        for col in range(0, size):
             if (row == col):
                print("1 ", end=" ")
             else:
                print("0 ", end=" ")
        print()

size = 4
Identity(size)

1  0  0  0  
0  1  0  0  
0  0  1  0  
0  0  0  1  


7. Create a 3x3 matrix with values ranging from 1 to 9.

In [ ]:
import numpy as np
x =  np.arange(1, 10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


8. Create 2 similar dimensional array and perform sum on them.

In [ ]:
import numpy as np

# Create a 2-dimensional array with 3 rows and 4 columns
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
Y = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
sum = np.array(X) + np.array(Y)
print(sum)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive.

In [ ]:
import datetime

start = datetime.datetime.strptime("01-02-2023", "%d-%m-%Y")
end = datetime.datetime.strptime("01-03-2023", "%d-%m-%Y")
date_generated = [start + datetime.timedelta(days=x) for x in range(0, (end-start).days)]

for date in date_generated:
    print (date.strftime("%d-%m-%Y"))

01-02-2023
02-02-2023
03-02-2023
04-02-2023
05-02-2023
06-02-2023
07-02-2023
08-02-2023
09-02-2023
10-02-2023
11-02-2023
12-02-2023
13-02-2023
14-02-2023
15-02-2023
16-02-2023
17-02-2023
18-02-2023
19-02-2023
20-02-2023
21-02-2023
22-02-2023
23-02-2023
24-02-2023
25-02-2023
26-02-2023
27-02-2023
28-02-2023


10. Given a dictionary, convert it into corresponding dataframe and display it
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240].

In [ ]:
import pandas as pd


data = {'Brand': ['Maruti', 'Renault', 'Hyndai'],
		'Sales': ['250', '200', '240']}
new = pd.DataFrame.from_dict(data)

print(new)


     Brand Sales
0   Maruti   250
1  Renault   200
2   Hyndai   240
